# Generated by Django 4.2.1 on 2023-06-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="elevatorsystem",
            old_name="name",
            new_name="system_name",
        ),
        migrations.RenameField(
            model_name="elevatorsystem",
            old_name="maximum_floors",
            new_name="total_floors",
        ),
    ]
