# Generated by Django 4.2.1 on 2023-06-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0002_rename_name_elevatorsystem_system_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elevator",
            name="running_status",
            field=models.IntegerField(
                choices=[(1, "Going Up"), (0, "Not Moving"), (-1, "Going Down")],
                default=0,
            ),
        ),
    ]
